baseURL = "https://www.colmryan.org/"
languageCode = "en-us"
title = "Tomorrow Said Toad"
copyright = "Â© Colm Ryan"
theme = "Eigen"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-158537342-1" 

[pagination]
  disableAliases = false
  pagerSize = 5
  path = 'page'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"

[author]
	name = "Colm Ryan"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
	subtitle = "Tomorrow said toad - today I will take life easy."
	mathjax = true


# Social Tags

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:colm@colmryan.org"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/caryan/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/caryan"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
